### ISSUE TITLE
Ability to import from ietf-ribose/bibxml-data-ieee

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-indexer#12]

**Comment by strogonoff** [comment]
This fails because we don’t have Relaton source configured, and we don’t use `relaton-bib-py` yet. Filed #25

**Comment by strogonoff** [comment]
Blocked and waits either for https://github.com/relaton/relaton-data-ieee or for #25.

**Comment by ronaldtse** [comment]
> This fails because we don’t have the Relaton source on Github apparently, and this service doesn’t use relaton-bib-py yet

Are you looking to have Relaton data for IEEE? The thing is the IETF does not want to provide the public with the full IEEE dataset contents. We can have a corresponding Relaton-formatted dataset for IEEE.

**Comment by ronaldtse** [comment]
I believe we could provide relaton-data-ieee from within the ietf-ribose organization.

**Comment by strogonoff** [comment]
> Are you looking to have Relaton data for IEEE?

Yes.

> The thing is the IETF does not want to provide the public with the full IEEE dataset contents.

But we have https://github.com/ietf-ribose/bibxml-data-ieee/tree/main/data, and it is set to be exposed through BibXML service public API, right? And since we have this dataset, we can handle conversion to Relaton on our side.

> We can have a corresponding Relaton-formatted dataset for IEEE.

But yeah, having Relaton data pre-made could speed up things a little in short term.

**Comment by strogonoff** [comment]
Works now (98f36e7f66f345b29aff2b7e63ade151631a17a0): http://34.229.41.119:8000/ieee/
